// Tech Radar data — ported from ../demo_tech_radar/data/radar.json
// Source of truth for the Tech → Tech Radar zone.
//
// Shape:
//   quadrants[]  — categories (index referenced by entry.quadrant)
//   rings[]      — maturity levels, innermost (Adopt) to outermost (Hold)
//   teams[]      — { id, label }
//   entries[]    — { name, quadrant, description, placements: { [teamId]: { ring, status?, note? } } }

export const radarData = {
  title: 'Tech Radar',
  quadrants: [
    'Languages & Frameworks',
    'Tools',
    'Platforms & Infrastructure',
    'Techniques',
  ],
  rings: ['Adopt', 'Trial', 'Assess', 'Hold'],
  teams: [
    { id: 'backend', label: 'Backend' },
    { id: 'cms', label: 'CMS' },
    { id: 'devops', label: 'DevOps' },
    { id: 'ad-sdk', label: 'Ad SDK' },
    { id: 'data-analytics', label: 'Data Analytics' },
    { id: 'data-engineers', label: 'Data Engineers' },
    { id: '1c', label: '1C Developers' },
  ],
  entries: [
    { name: 'PHP 8.3', quadrant: 0, description: 'Primary backend language. On 8.3 with typed properties, enums and readonly classes.', placements: { backend: { ring: 0 } } },
    { name: 'Laravel', quadrant: 0, description: 'Default framework for new backend services and APIs.', placements: { backend: { ring: 0 } } },
    { name: 'Symfony', quadrant: 0, description: 'Used in select services; evaluating its components for shared libraries.', placements: { backend: { ring: 1 } } },
    { name: 'Go', quadrant: 0, description: 'Assessing for high-throughput, low-latency services (bid handling, edge).', placements: { backend: { ring: 2, status: 'new' }, 'ad-sdk': { ring: 1, status: 'new', note: 'Backend-for-frontend services behind the SDK.' } } },
    { name: 'Swift', quadrant: 0, description: 'Native iOS SDK development.', placements: { 'ad-sdk': { ring: 0 } } },
    { name: 'Kotlin', quadrant: 0, description: 'Native Android SDK development.', placements: { 'ad-sdk': { ring: 0 } } },
    { name: 'C++', quadrant: 0, description: 'Shared cross-platform core for performance-critical SDK code.', placements: { 'ad-sdk': { ring: 1 } } },
    { name: 'Kotlin Multiplatform', quadrant: 0, description: 'Assessing to share logic between Android and iOS SDKs.', placements: { 'ad-sdk': { ring: 2, status: 'new' } } },
    { name: 'Python', quadrant: 0, description: 'Standard language for analytics, ETL and tooling.', placements: { 'data-analytics': { ring: 0 }, 'data-engineers': { ring: 0 } } },
    { name: 'SQL', quadrant: 0, description: 'Core query language across analytics and engineering.', placements: { 'data-analytics': { ring: 0 }, 'data-engineers': { ring: 0 }, backend: { ring: 0 } } },
    { name: 'Twig', quadrant: 0, description: 'Templating for server-rendered CMS pages.', placements: { cms: { ring: 0 } } },
    { name: 'Vue.js', quadrant: 0, description: 'Interactive front-end widgets on top of CMS pages.', placements: { cms: { ring: 1 } } },
    { name: 'Tailwind CSS', quadrant: 0, description: 'Trialling for faster, consistent styling of marketing sites.', placements: { cms: { ring: 1, status: 'new' } } },
    { name: 'jQuery', quadrant: 0, description: 'Legacy only. Do not start new work with it; migrate to Vue where feasible.', placements: { cms: { ring: 3, status: 'moved-out' } } },
    { name: '1C:Enterprise (BSL)', quadrant: 0, description: 'Primary platform and language for ERP/accounting development.', placements: { '1c': { ring: 0 } } },
    { name: 'Docker', quadrant: 1, description: 'Standard for packaging and local development.', placements: { devops: { ring: 0 }, backend: { ring: 0 }, 'data-engineers': { ring: 0 } } },
    { name: 'Terraform', quadrant: 1, description: 'Infrastructure as code across all environments.', placements: { devops: { ring: 0 } } },
    { name: 'GitLab CI', quadrant: 1, description: 'Primary CI/CD pipeline tooling.', placements: { devops: { ring: 0 }, backend: { ring: 0 } } },
    { name: 'Prometheus', quadrant: 1, description: 'Metrics collection and alerting.', placements: { devops: { ring: 0 } } },
    { name: 'Grafana', quadrant: 1, description: 'Dashboards and observability.', placements: { devops: { ring: 0 } } },
    { name: 'Helm', quadrant: 1, description: 'Kubernetes package/release management.', placements: { devops: { ring: 0 } } },
    { name: 'ArgoCD', quadrant: 1, description: 'Trialling GitOps-based continuous delivery.', placements: { devops: { ring: 1, status: 'new' } } },
    { name: 'Ansible', quadrant: 1, description: 'Config management for non-containerised hosts.', placements: { devops: { ring: 1 } } },
    { name: 'HashiCorp Vault', quadrant: 1, description: 'Assessing for centralised secrets management.', placements: { devops: { ring: 2, status: 'new' }, backend: { ring: 2, status: 'new' } } },
    { name: 'Apache Airflow', quadrant: 1, description: 'Batch pipeline orchestration.', placements: { 'data-engineers': { ring: 0 } } },
    { name: 'dbt', quadrant: 1, description: 'Trialling for version-controlled, tested data transformations.', placements: { 'data-engineers': { ring: 1, status: 'new' }, 'data-analytics': { ring: 2, status: 'new', note: 'Just piloting; most modeling still raw SQL.' } } },
    { name: 'Metabase', quadrant: 1, description: 'Self-serve BI and dashboards for stakeholders.', placements: { 'data-analytics': { ring: 0 } } },
    { name: 'Apache Superset', quadrant: 1, description: 'Trialling for richer exploration alongside Metabase.', placements: { 'data-analytics': { ring: 1 } } },
    { name: 'Jupyter', quadrant: 1, description: 'Ad-hoc analysis and prototyping.', placements: { 'data-analytics': { ring: 0 } } },
    { name: 'Power BI', quadrant: 1, description: 'Maintained for existing finance reports only; consolidate on Metabase.', placements: { 'data-analytics': { ring: 3 } } },
    { name: '1C:EDT', quadrant: 1, description: 'Trialling Eclipse-based IDE to enable Git workflows.', placements: { '1c': { ring: 1, status: 'new' } } },
    { name: 'ProGuard / R8', quadrant: 1, description: 'Shrinking and obfuscation for Android SDK builds.', placements: { 'ad-sdk': { ring: 1 } } },
    { name: 'PostgreSQL', quadrant: 2, description: 'Default relational database for services.', placements: { backend: { ring: 0 }, 'data-analytics': { ring: 0 } } },
    { name: 'Redis', quadrant: 2, description: 'Caching, rate limiting and ephemeral state.', placements: { backend: { ring: 0 } } },
    { name: 'RabbitMQ', quadrant: 2, description: 'Async messaging between services.', placements: { backend: { ring: 1 } } },
    { name: 'Kubernetes', quadrant: 2, description: 'Container orchestration for production workloads.', placements: { devops: { ring: 0 }, backend: { ring: 1, status: 'new', note: 'Migrating remaining services off VMs.' } } },
    { name: 'Apache Kafka', quadrant: 2, description: 'Event streaming backbone for telemetry and pipelines.', placements: { 'data-engineers': { ring: 0 }, 'ad-sdk': { ring: 2, status: 'new', note: 'Evaluating for SDK telemetry ingest.' } } },
    { name: 'ClickHouse', quadrant: 2, description: 'Columnar store for analytics over large event volumes.', placements: { 'data-engineers': { ring: 0 }, 'data-analytics': { ring: 1, note: 'Trialling for self-serve dashboards.' } } },
    { name: 'Apache Spark', quadrant: 2, description: 'Large-scale batch processing.', placements: { 'data-engineers': { ring: 1 } } },
    { name: 'Apache Flink', quadrant: 2, description: 'Assessing for stateful stream processing.', placements: { 'data-engineers': { ring: 2, status: 'new' } } },
    { name: 'Apache Iceberg', quadrant: 2, description: 'Assessing open table format for the lakehouse.', placements: { 'data-engineers': { ring: 2, status: 'new' } } },
    { name: 'S3-compatible object storage', quadrant: 2, description: 'Durable storage for data lake and backups.', placements: { 'data-engineers': { ring: 0 }, devops: { ring: 0 } } },
    { name: 'WordPress', quadrant: 2, description: 'Marketing sites and blogs.', placements: { cms: { ring: 1 } } },
    { name: 'Strapi (Headless CMS)', quadrant: 2, description: 'Assessing headless content for omni-channel delivery.', placements: { cms: { ring: 2, status: 'new' } } },
    { name: 'Google Mobile Ads / Mediation', quadrant: 2, description: 'Core mediation platform for ad delivery.', placements: { 'ad-sdk': { ring: 0 } } },
    { name: 'Unity Ads', quadrant: 2, description: 'Assessing for the gaming inventory segment.', placements: { 'ad-sdk': { ring: 2 } } },
    { name: 'REST APIs', quadrant: 3, description: 'Default style for service interfaces.', placements: { backend: { ring: 0 } } },
    { name: 'gRPC', quadrant: 3, description: 'Internal service-to-service calls where latency matters.', placements: { backend: { ring: 1 } } },
    { name: 'GraphQL', quadrant: 3, description: 'Assessing for aggregating data for front-ends.', placements: { backend: { ring: 2 }, cms: { ring: 2 } } },
    { name: 'OpenRTB', quadrant: 3, description: 'Standard protocol for real-time bidding integration.', placements: { 'ad-sdk': { ring: 0 } } },
    { name: 'Header Bidding', quadrant: 3, description: 'Trialling to increase fill and yield.', placements: { 'ad-sdk': { ring: 1 } } },
    { name: 'Change Data Capture (Debezium)', quadrant: 3, description: 'Assessing CDC to stream DB changes into the lake.', placements: { 'data-engineers': { ring: 2, status: 'new' }, backend: { ring: 2, status: 'new' } } },
    { name: 'Trunk-Based Development', quadrant: 3, description: 'Trialling short-lived branches and frequent integration.', placements: { backend: { ring: 0, note: 'Standard practice; short-lived branches only.' }, 'ad-sdk': { ring: 1 }, cms: { ring: 1 } } },
    { name: 'Infrastructure as Code', quadrant: 3, description: 'All infrastructure changes go through code review.', placements: { devops: { ring: 0 } } },
    { name: 'Version Control for 1C (Git)', quadrant: 3, description: 'Trialling Git-based workflows via 1C:EDT instead of stored configs.', placements: { '1c': { ring: 1, status: 'new' } } },
    { name: 'Automated Testing for 1C (Vanessa)', quadrant: 3, description: 'Assessing BDD-style automated testing for 1C solutions.', placements: { '1c': { ring: 2, status: 'new' } } },
  ],
};
